ci: wait for dyndnsd gem to be available on rubygems.org before Docker build

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -12,11 +12,22 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - run: sleep 30
-
     - name: Extract dyndnsd version from tag name
       run: |
         echo "DYNDNSD_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
+
+    - name: Wait for dyndnsd ${{ env.DYNDNSD_VERSION }} gem to be available
+      run: |
+        set +e
+        for retry in $(seq 1 5); do
+          echo "Checking if dyndnsd $DYNDNSD_VERSION gem is retrievable from rubygems.org (try #$retry)..."
+          sudo gem install dyndnsd -v "$DYNDNSD_VERSION"
+          if [ $? -eq 0 ]; then
+            exit 0
+          fi
+          sleep 60
+        done
+        exit 1
 
     # https://github.com/marketplace/actions/build-and-push-docker-images
     - name: Set up Docker Buildx
